name: Terraform and Terratest

on:
  push:
    branches:
      - main
      - features
      - develop
      - test
  pull_request:
    branches:
      - main
      - features
      - develop
      - test

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.18", "1.19"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install Terraform
      run: |
        sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install terraform

    - name: Initialize Go module
      run: go mod init github.com/kennyr3221/terra-temp || true

    - name: Get dependencies
      run: |
        export GIT_LFS_SKIP_SMUDGE=1
        go clean -modcache
        go get github.com/gruntwork-io/terratest/modules/terraform@v0.46.15
        go get github.com/stretchr/testify/assert@v1.8.4
        go mod tidy
        go mod vendor

    - name: Run Terratest for iaac-sample-1
      run: |
        cd test
        go test -v -run TestTerraformIaacSample1

    - name: Run Terratest for iaac-sample-2
      run: |
        cd test
        go test -v -run TestTerraformIaacSample2

    - name: Terraform Init for iaac-sample-1
      run: terraform init
      working-directory: ./iaac-sample-1

    - name: Terraform Apply for iaac-sample-1
      run: terraform apply -auto-approve
      working-directory: ./iaac-sample-1

    - name: Terraform Destroy for iaac-sample-1
      run: terraform destroy -auto-approve
      working-directory: ./iaac-sample-1

    - name: Terraform Init for iaac-sample-2
      run: terraform init
      working-directory: ./iaac-sample-2

    - name: Terraform Apply for iaac-sample-2
      run: terraform apply -auto-approve
      working-directory: ./iaac-sample-2

    - name: Terraform Destroy for iaac-sample-2
      run: terraform destroy -auto-approve
      working-directory: ./iaac-sample-2
